INSERT INTO genres (id, name) SELECT 1, 'Комедия' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 1 AND name = 'Комедия')
INSERT INTO genres (id, name) SELECT 2, 'Драма' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 2 AND name = 'Драма')
INSERT INTO genres (id, name) SELECT 3, 'Мультфильм' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 3 AND name = 'Мультфильм')
INSERT INTO genres (id, name) SELECT 4, 'Триллер' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 4 AND name = 'Триллер')
INSERT INTO genres (id, name) SELECT 5, 'Документальный' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 5 AND name = 'Документальный')
INSERT INTO genres (id, name) SELECT 6, 'Боевик' WHERE NOT EXISTS (SELECT 1 FROM genres WHERE id = 6 AND name = 'Боевик')

INSERT INTO ratings (id, name) SELECT 1, 'G' WHERE NOT EXISTS (SELECT 1 FROM ratings WHERE id = 1 AND name = 'G')
INSERT INTO ratings (id, name) SELECT 2, 'PG' WHERE NOT EXISTS (SELECT 1 FROM ratings WHERE id = 2 AND name = 'PG')
INSERT INTO ratings (id, name) SELECT 3, 'PG-13' WHERE NOT EXISTS (SELECT 1 FROM ratings WHERE id = 3 AND name = 'PG-13')
INSERT INTO ratings (id, name) SELECT 4, 'R' WHERE NOT EXISTS (SELECT 1 FROM ratings WHERE id = 4 AND name = 'R')
INSERT INTO ratings (id, name) SELECT 5, 'NC-17' WHERE NOT EXISTS (SELECT 1 FROM ratings WHERE id = 5 AND name = 'NC-17')
