CREATE TABLE IF NOT EXISTS users (id INTEGER AUTO_INCREMENT, name VARCHAR, login VARCHAR, email VARCHAR, birthday DATE)

CREATE TABLE IF NOT EXISTS friends (user_id INTEGER, friend_id INTEGER)

CREATE TABLE IF NOT EXISTS films (id INTEGER, name VARCHAR, description TEXT, release DATE, duration INTEGER, rating VARCHAR)

CREATE TABLE IF NOT EXISTS likes (user_id INTEGER, film_id INTEGER)

CREATE TABLE IF NOT EXISTS genres (id INTEGER AUTO_INCREMENT PRIMARY KEY, genre VARCHAR UNIQUE)

CREATE TABLE IF NOT EXISTS films_genres (film_id INTEGER, genre_id INTEGER)