CREATE TABLE IF NOT EXISTS users (id INTEGER, name VARCHAR, login VARCHAR, email VARCHAR, birthday VARCHAR)

CREATE TABLE IF NOT EXISTS friends (user_id INTEGER, friend_id INTEGER)

CREATE TABLE IF NOT EXISTS films (id INTEGER, name VARCHAR, description TEXT, release VARCHAR, duration INTEGER, rating_id INTEGER)

CREATE TABLE IF NOT EXISTS likes (user_id INTEGER, film_id INTEGER)

CREATE TABLE IF NOT EXISTS genres (id INTEGER, name VARCHAR)

CREATE TABLE IF NOT EXISTS films_genres (film_id INTEGER, genre_id INTEGER)

CREATE TABLE IF NOT EXISTS ratings (id INTEGER, name VARCHAR)